name: Manual lessons trigger
on:
  workflow_dispatch:
    inputs:
      lesson-type:
        default: "Practice"
        description: 'Type of lesson'
        required: true
        type: choice
        options:
          - "Skill"
          - "Practice"
      lessons:
        default: 0
        description: 'Number of lessons'
        required: true
        type: number
   
jobs:
  Manual:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4    
      - name: Run DuoXPy
        run: python main.py
        env:
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
          LESSONS: ${{ inputs.lessons }}
          LESSON-TYPE: ${{ inputs.lesson-type }}
